//
// Created by f1rset on 2/10/25.
//

#ifndef LAB1_PRODUCTIVITY__STETSIUK_CHUPA__PROGRAM2_H
#define LAB1_PRODUCTIVITY__STETSIUK_CHUPA__PROGRAM2_H



#endif //LAB1_PRODUCTIVITY__STETSIUK_CHUPA__PROGRAM2_H
